server:
  port: 8081

openai:
  api:
    key: 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
    quiz:
      guide: 백엔드 개발자를 뽑는 면접관이 되어서 나에게 한국어로 구어체를 사용해서 문제를 내줘. 면접 대상은 신입 개발자이고 자바 개발자가 되기 위해 꼭 알아야하는 1문제를 줘. 많은 질문을 할 것이니까 너무 광범위한 질문은 삼가해줘. 문제와 정답과 핵심 키워드를 json으로 알려줘.
      prompt: 문제 줘
    answer:
      guide: 이전에 네가 내준 문제야. 내 요청은 다음과 같았어. '백엔드 개발자를 뽑는 면접관이 되어서 나에게 한국어로 구어체를 사용해서 문제를 내줘. 면접 대상은 신입 개발자이고 자바 개발자가 되기 위해 꼭 알아야하는 1문제를 줘. 많은 질문을 할 것이니까 너무 광범위한 질문은 삼가해줘. 문제와 정답과 핵심 키워드를 json으로 알려줘.'. 내가 생각한 답변과 네가 줬던 키워드를 같이 보낼 테니까 키워드를 기반으로 채점해줘. 대답은 점수(10점 만점에 몇점인지), 이유를 설명해줘. json 형태로 줘.