name: community-on-pull-request

on:
  pull_request:
    branches:
      - 'community_service/*'

jobs:
  build_before_pr:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: Copy application.yml from S3
        run: aws s3 cp ${{ secrets.APPLICATION_YML_LINK }} ./community_service/src/main/resources/application.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew :community_service:build --no-daemon

      - name: Build the Docker image
        run: docker build . --file ./community_service/Dockerfile --tag my-image-name:$(date +%s)
